name: "build and deploy docker image"

on:
  push:
    tags:
      - "*" # Trigger on any tag push

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Verify extracted tag
        run: echo "Using TAG_NAME=${{ env.TAG_NAME }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tankittipat/ci-project:${{ env.TAG_NAME }}
            ghcr.io/tankittipat/ci-project:latest
